### PR TITLE
package.json file

### PR DESCRIPTION
**Pull request by esayemm**
Put a little package.json file together for ya, all that's left to do is publish through npm.

[how to publish on npm](https://gist.github.com/coolaj86/1318304)

Thanks!

### CODE REVIEW

**Comment by marczking** [comment]
nice! +1

**Comment by stephenhutchings** [comment]
I had some reservations about this, concerning whether npm is the right place for these assets, but this [post](http://blog.npmjs.org/post/101775448305/npm-and-front-end-packaging) seems to promote hosting such front-end assets. Will publish to npm when I have a chance, but merging in the meantime.

**Comment by neurotech** [comment]
If I use `npm install typicons.font` all it installs in `node_modules/typicons.font` is `package.json` and `README.md`.

Can this be resolved, please?

**Comment by stephenhutchings** [comment]
Sorry about that. The directories in the package file array were added incorrectly. This is fixed in now with v2.0.8 @neurotech.

**Comment by neurotech** [comment]
Beautiful, thank you @stephenhutchings 👍

**Pull request merged**
